name: Crawl bus tour

on:
  workflow_dispatch:
  #schedule:
  #- cron: '0 0 * * *'
jobs:
  crawl-bus-tour:
    name: crawl-bus-tour
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install python runtime
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Install aws cli
      uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true


    - name: Crawl HIS bus tour
      run: |
        aws s3 cp s3://${{ secrets.CRAWLER_BUCKET_NAME }}/${{ secrets.PARAMS_DIR }}${{ secrets.PARAMS_FILE }} .
        ./crawl_detail_urls.py ${{ secrets.PARAMS_FILE }} <( echo '
          {
            "type": "s3",
            "key": "${{ secrets.AWS_S3_ACCESS_KEY_ID }}",
            "secret": "${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}",
            "bucket_name": "${{ secrets.CRAWLER_BUCKET_NAME }}",
            "dir": "${{ secrets.URLS_DIR }}"
          }
        ')
        aws s3 cp s3://${{ secrets.CRAWLER_BUCKET_NAME }}/${{ secrets.URLS_DIR }}detail_urls.json .
        ./crawl_detail.py detail_urls.json <(echo '
          {
            "type": "s3",
            "key": "${{ secrets.AWS_S3_ACCESS_KEY_ID }}",
            "secret": "${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}",
            "bucket_name": "${{ secrets.CRAWLER_BUCKET_NAME }}",
            "dir": "${{ secrets.RESULTS_DIR }}"
          }
        ')
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
