name: Crawl bus tour

on:
  schedule:
  - cron: '0 * * * *'
jobs:
  crawl-bus-tour:
    name: crawl-bus-tour
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install venv
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Crawl HIS bus tour
      run: | 
        ./crawl_detail_urls.py
        ./crawl_detail.py detail_urls.json

    - name: Upload results
      uses: chrislennon/action-aws-cli@v1.1
    - run: ls bus_tour* | xargs -I {} aws s3 cp {} ${{ secrets.CRAWLER_BUCKET_URL }}/tour_details/
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

