name: Crawl search parameters

on:
  workflow_dispatch:
jobs:
  crawl-search-params:
    name: crawl-search-params
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install python runtime
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
    - name: Install aws cli
      uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Crawl search params
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/mi_comet_crawler:0.1
        options: -v ${{ github.workspace }}:/project
        run: |
          cd /project
          python3 crawl_search_options.py

    - name: Upload results
      run: ls *.json | xargs -I {} aws s3 cp {} ${{ secrets.CRAWLER_BUCKET_URL }}/search_params/
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
