name: Crawl search parameters

on:
  workflow_dispatch:
jobs:
  crawl-search-params:
    name: crawl-search-params
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Crawl search params
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/mi_comet_crawler:0.2
        options: -v ${{ github.workspace }}:/project -v /github/home:/pj2
        run: |
          cd /project
          echo $(cat <<EOF
            {
              "type": "s3",
              "key": "${{ secrets.AWS_S3_ACCESS_KEY_ID }}",
              "secret": "${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}",
              "bucket_name": "${{ secrets.CRAWLER_BUCKET_NAME }}",
              "dir": "${{ secrets.PARAM_OPTIONS_DIR }}"
            }
          EOF
          ) > s3_config.json
          python3 crawl_search_options.py s3_config.json
