name: General crawler

on:
    workflow_dispatch:
        inputs:
            image:
                description: "base image to run the crawler"
                required: true
            script:
                description: "the script to run(end by .py)"
                required: true
            storage_config:
                description: "informations of a storage to restore the dat a crawled(json, encoded in base64)"
                requried: true
            crawl_config:
                description: "informations to use for searching(json, encoded in base64)"
                required: true
jobs:
    general-crawler:
        name: general-crawler
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: prepare config files
              run: |
                  echo "$crawl_config" | base64 -d > crawl_config.json
                  echo "$storage_config" | base64 -d > storage_config.json
              env:
                  crawl_config: "${{ github.event.inputs.crawl_config }}"
                  storage_config: "${{ github.event.inputs.storage_config }}"

            - name: crawl data
              uses: addnab/docker-run-action@v3
              with:
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image }}
                  options: -v ${{ github.workspace }}:/project -v /github/home:/pj2
                  run: |
                      cd /project

                      python3 ${{ github.event.inputs.script }} storage_config.json crawl_config.json

                      rm crawl_config.json storage_config.json
